### ISSUE TITLE
Missing permissions

### ISSUE THREAD

**Issue by sdtokkolabs** [previousnext/k8s-aws-efs#11]
There are at least 3 missing permissions for using efs's "CreateMount" on the proposed security policy:
* ec2:DescribeSubnets
* ec2:DescribeNetworkInterfaces
* ec2:CreateNetworkInterface

https://docs.aws.amazon.com/sdk-for-go/api/service/efs/#EFS.CreateMountTarget

Docs should be updated

**Comment by nickschuch** [comment]
Policy has been updated:

https://github.com/previousnext/k8s-aws-efs/commit/3f170e79f20402093116aa60028a7dc0ba316b16
